language: python
python:
  - "3.4"
install:
  - pip install nose
script:
  - python setup.py install
  - nosetests
notifications:
  email:
    - naumann@eva.mpg.de
    - lena_sell@eva.mpg.de
    - noemie_jaulgey@eva.mpg.de
    - robert_forkel@eva.mpg.de
